### ISSUE TITLE
Try to check the content of the archive with: cat /opt/nextron/thunderstorm/thor.zip 

### ISSUE THREAD

**Issue by resteex0** [NextronSystems/thor-lite#10]
Extracting THOR package to /opt/nextron/thunderstorm ... 
[/opt/nextron/thunderstorm/thor.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /opt/nextron/thunderstorm/thor.zip or
        /opt/nextron/thunderstorm/thor.zip.zip, and cannot find /opt/nextron/thunderstorm/thor.zip.ZIP, period.
Extraction of THOR package failed. 
Try to check the content of the archive with: cat /opt/nextron/thunderstorm/thor.zip

**Comment by Neo23x0** [comment]
Thunderstorm? 
Don't download THOR Thunderstorm. 
You don't get a license for that. Download THOR Lite. 
https://www.nextron-systems.com/thor-lite/download/

**Comment by resteex0** [comment]
today when loggin to my linux is appear this massage under box of password login of system ,
"thunderstorm service user"

you edit of linux kernal ? or something hidden service traffic as rootkit ? please explain how this massage appear to me

**Comment by resteex0** [comment]
> Extracting THOR package to /opt/nextron/thunderstorm ... [/opt/nextron/thunderstorm/thor.zip] End-of-central-directory signature not found. Either this file is not a zipfile, or it constitutes one disk of a multi-part archive. In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive. unzip: cannot find zipfile directory in one of /opt/nextron/thunderstorm/thor.zip or /opt/nextron/thunderstorm/thor.zip.zip, and cannot find /opt/nextron/thunderstorm/thor.zip.ZIP, period. Extraction of THOR package failed. Try to check the content of the archive with: cat /opt/nextron/thunderstorm/thor.zip

i download license already but sinstallation not discover yet

please refer to installation guide by video YouTube link

**Comment by Neo23x0** [comment]
You've installed the wrong product. You've installed THOR Thunderstorm. 

Please download and install THOR Lite
https://www.youtube.com/watch?v=C0absUumKlQ

You should also run 
```
sudo ./thunderstorm-installer.sh uninstall
```
to remove the user and the service of the wrong product.

**Comment by resteex0** [comment]
> today when loggin to my linux is appear this massage under box of password login of system , "thunderstorm service user"
> 
> you edit of linux kernal ? or something hidden service traffic as rootkit ? please explain how this massage appear to me

@Neo23x0 please I don’t know how this massage appear !

**Comment by Neo23x0** [comment]
You've installed a completely different product and that product added a user account to your workstation.
The installer even says that and you have to confirm that message.
