### ISSUE TITLE
Error undefined identifier "owner"

### ISSUE THREAD

**Issue by fareedfauzi** [NextronSystems/thor-lite#11]
I ran the THOR lite using KAPE module and the scan result gave me this error.

![image](https://user-images.githubusercontent.com/56353946/154079320-11cfa6ca-c5de-4078-a375-4debb324cfc6.png)

Anyone know why?

**Comment by Neo23x0** [comment]
That's a very important signature file. 
Could you tell me which THOR Version you use? 
(Screenshot of the header of that HTML report)

Background: "owner" is an external variable used in some YARA matching steps and should be supported by every newer THOR version. 

Did you run 
```
thor-lite-util.exe upgrade
```
from time to time? 

Some users only update the signature pack and not the binary. (for years)

**Comment by fareedfauzi** [comment]
The version of my THOR is 10.5.12

![image](https://user-images.githubusercontent.com/56353946/154102519-9fd577ae-a9de-46e7-ad2b-d3a625d0b4c4.png)

**Comment by Neo23x0** [comment]
That's a pretty old version of THOR. See my update in the reply above. 
It seems that you haven't updated the program files for at least more than 12 months.

**Comment by fareedfauzi** [comment]
I see.. Okay. I close the issue for now. Will open back if the error still occur. Thanks a lot Sir!
