### ISSUE TITLE
How to upgrade the license 

### ISSUE THREAD

**Issue by Add2502** [NextronSystems/thor-lite#12]
I have locate the license .lic in a folder but when i try to run the command "thor-util upgrade" to upgrade license, the "command not found". pls help me on this

**Comment by Neo23x0** [comment]
What do you mean by "upgrade the license"? 

You can update THOR Lite and its signatures using 

```
thor-lite-util.exe upgrade
```

**Comment by meemakwana** [comment]
Hi, 

I am facing the below-mentioned issues while upgrading the thor-lite, looks like we need to update the license key.

How can we fix this issue? I apply for a download, but I get files to download email without a license key.

Aug  2 04:18:57 <server> THOR_LITE_UTIL: Info: Starting Upgrade Process
Aug  2 04:18:57 <server> THOR_LITE_UTIL: Info: License file found OWNER: Meena Makwana (xx.com) TYPE: THOR Lite STARTS: 2021/06/16 EXPIRES: 2022/06/24
Aug  2 04:18:57 <server> THOR_LITE_UTIL: Info: License file C:\NEXTRON\thor10lite-win-pack\licenses\MM.com.lic not applicable: license expired
Aug  2 04:18:57 <server> THOR_LITE_UTIL: Error: No valid license found

**Comment by Neo23x0** [comment]
You've also sent us the email with the link to the new license to our customer support portal. 
Just click on that link and download the new license. It works. I've tested it.
