### ISSUE TITLE
custom-keywords.txt.template is boosting Mimikatz_Memory_Rule_2 false positives rate

### ISSUE THREAD

**Issue by marcobellaccini** [NextronSystems/thor-lite#18]
Hi,
I know that false positives are unavoidable in a tool like thor-lite.

Still, I have a suggestion for reducing the false-positives triggered by [Mimikatz_Memory_Rule_2](https://github.com/Yara-Rules/rules/blob/3872244500f584491cde7c633f12f1f043a61c13/malware/TOOLKIT_THOR_HackTools.yar#L2895).

That rule is looking for the string "_sekurlsa::_" and at least one of other four strings.

Unfortunately, due to the fact that the "_sekurlsa::_" string is contained in plaintext form in one of the examples in the file _custom-keywords.txt.template_ (bundled with the thor-lite zip archive), finding that string in _Explorer.exe_ memory is very frequent.
This boosts false positives rate because it makes the first (and most targeted) part of the rule almost always matched.

It would be nice if that string was removed from that file or modified in order to fail the match.

Cheers

Marco

**Comment by Neo23x0** [comment]
Thanks. We'll do that.

**Comment by secDre4mer** [comment]
I've modified the template file and it'll no longer contain the _sekurlsa::_ string in the next release.
