### ISSUE TITLE
Possible certificate problem on update server

### ISSUE THREAD

**Issue by FractalArt** [NextronSystems/thor-lite#23]
I tried to upgrade my thor-lite (Linux):

```sh
> ./thor-lite-util upgrade
```

I got the following error:

```sh
Info: Downloading from: https://update-lite.nextron-systems.com/getliteupdate.php?<REDACTED>
THOR_LITE_UTIL: Error: download failed: x509: certificate has expired or is not yet valid: current time 2023-03-11T23:39:51+01:00 is after 2023-03-10T23:59:59Z
THOR_LITE_UTIL: Error: Download failed: No update possible with this update server
```

and wanted to ask whether there is indeed a problem with the update server certificate or whether there is a problem on my side.

**Comment by pat00x** [comment]
Hi @FractalArt !
Thanks in first place for using THOR Lite and reporting this issue.
We checked and it should have been resolved , please let us know in case it isn't.

Have a great start of the week
pat00x

**Comment by FractalArt** [comment]
Thank you! It is working :slightly_smiling_face:
