### ISSUE TITLE
Timestamp in log file - UTC

### ISSUE THREAD

**Issue by a2tf** [NextronSystems/thor-lite#3]
Hi All

I started using the current thor lite version in splunk and ingested the written log files. Is it by design that the timestamps in the log file are in UTC timezone? Begin Time and End Time of the scan are in system local time written to the log file. 

If that's the way it's meant to be, then I will change the timezone in the splunk add-on to UTC.

Thanks in advance,

Andi

**Comment by Neo23x0** [comment]
Hi and thanks for reporting that bug. 
We will fix that in the next version. 
Since we're about to release v10.5 today, this will be in the next release in July.

**Comment by Neo23x0** [comment]
Hi, 
you can use the `--utc` command line flag to also get the timestamps in the log lines to UTC. There is no option to adjust all timestamps the other way around.
