### ISSUE TITLE
Decryption errors with signatures

### ISSUE THREAD

**Issue by Krow10ca** [NextronSystems/thor-lite#39]
Following the update to the signatures using the thor-lite-util.exe on Windows, scans using thor64-lite.exe and thor-lite.exe are returning errors related to decryption of the YARA and IOC signatures. The end result is that no signatures are loaded and scans are quickly completed.

Tested on both Windows 11 and Windows Server 2016 with the same result. Using an older version of the signatures works as expected, but following an update the issue is introduced.

THOR 10.7.14
Build aeb71a6 (2024-02-06 14:10:17) (windows, amd64)
YARA 4.3.2
PE-Sieve 0.3.5
OpenSSL 3.0.9
Signature Database 2024/03/15-142046

> Reading YARA signatures and IOC files ...
Info Adding rule set from thor-lite-all.yas as 'default' type
Error Could not decrypt yara rule
FILE: C:\temp\thor_lite_dist\signatures\yara\thor-lite-all.yas ERROR: could not decode session key: crypto/rsa: decryption error
Info Adding rule set from thor-lite-deepscan-selectors.yasx as 'meta' type
Error Could not decrypt yara rule
FILE: C:\temp\thor_lite_dist\signatures\yara\thor-lite-deepscan-selectors.yasx ERROR: could not decode session key: crypto/rsa: decryption error
Info Adding rule set from thor-lite-keywords.yas as 'keyword' type
Error Could not decrypt yara rule
FILE: C:\temp\thor_lite_dist\signatures\yara\thor-lite-keywords.yas ERROR: could not decode session key: crypto/rsa: decryption error
Info Adding rule set from thor-lite-log-sigs.yas as 'log' type
Error Could not decrypt yara rule
FILE: C:\temp\thor_lite_dist\signatures\yara\thor-lite-log-sigs.yas ERROR: could not decode session key: crypto/rsa: decryption error
Info Adding rule set from thor-lite-meta.yas as 'meta' type
Error Could not decrypt yara rule
FILE: C:\temp\thor_lite_dist\signatures\yara\thor-lite-meta.yas ERROR: could not decode session key: crypto/rsa: decryption error
Info Adding rule set from thor-lite-peids.yas as 'default' type
Error Could not decrypt yara rule
FILE: C:\temp\thor_lite_dist\signatures\yara\thor-lite-peids.yas ERROR: could not decode session key: crypto/rsa: decryption error
Info Adding rule set from thor-lite-process-memory-sigs.yas as 'process' type
Error Could not decrypt yara rule
FILE: C:\temp\thor_lite_dist\signatures\yara\thor-lite-process-memory-sigs.yas ERROR: could not decode session key: crypto/rsa: decryption error
Info Adding rule set from thor-lite-registry.yas as 'registry' type
Error Could not decrypt yara rule
FILE: C:\temp\thor_lite_dist\signatures\yara\thor-lite-registry.yas ERROR: could not decode session key: crypto/rsa: decryption error
Info Skip sigma initialization, use '--sigma' flag to scan with sigma
Error Could not decrypt ioc file
FILE: C:\temp\thor_lite_dist\signatures\iocs\c2-iocs.dat ERROR: could not decode session key: crypto/rsa: decryption error
Error Could not walk through ioc signature directories ERROR: could not decode session key: crypto/rsa: decryption error
Info Successfully compiled 0 keyword ioc strings TYPE: IOC
Info Successfully compiled 0 filename ioc strings and 0 filename ioc regexs TYPE: IOC
Info Successfully compiled 0 malware and 0 false positive hashes TYPE: IOC
Info Successfully compiled 0 file type signatures TYPE: IOC
Info Successfully compiled 0 malware domains TYPE: IOC
Info Successfully compiled 0 named pipe ioc strings and 0 named pipe ioc regexs TYPE: IOC
Info Successfully compiled 0 malicious handles and 0 regex malicious handles TYPE: IOC
Warning No file type signatures compiled, file type detection can't be done. Because of this, many files won't be scanned.
Info No custom registry excludes defined
Info No custom eventlog excludes defined
Info No custom process excludes defined
Info Successfully compiled 0 default YARA rules TYPE: YARA
Info Successfully compiled 0 custom default YARA rules TYPE: YARA
Info Successfully compiled 0 meta YARA rules TYPE: YARA
Info Successfully compiled 0 process YARA rules TYPE: YARA
Info Successfully compiled 0 log YARA rules TYPE: YARA
Info Successfully compiled 0 registry YARA rules TYPE: YARA
Info Successfully compiled 0 keyword YARA rules TYPE: YARA

**Comment by CaptainComeback** [comment]
Same thing using Thor-lite on Mac OS 14.4 
Info Thor Version: 10.7.14
Info Thor Build: aeb71a63996a (2024-02-06 04:05:42)

**Comment by Neo23x0** [comment]
Thanks for reporting this. We're working on this. It was caused by a change that aims to decrease the time it takes to initialise the signature set by using the same key for all encrypted signature files instead of using a custom key for each file. 

We'll push a fix in <2h 

PS: the set of tests for THOR Lite signature release packages is still limited. We'll try to implement some of the checks that we do for the THOR Enterprise signature release for the "Lite" versions, too.

**Comment by Krow10ca** [comment]
Happy to report all is working again. Thanks @Neo23x0!

**Comment by CaptainComeback** [comment]
It is working great thank you. Thank you for creating the best free tool for the home user I appreciate it very much.
