### ISSUE TITLE
Integration Thor with Velociraptor

### ISSUE THREAD

**Issue by coos60** [NextronSystems/thor-lite#40]
Hello everyone,
I downloaded the yaml files from the repository, compressed them into a zip file and uploaded them to velociraptor. I cannot use any of the preconfigured scanners as they ask for api keys which I do not have. I have to give a talk on this and need to show the functionality.
Thank you.

**Comment by pH-T** [comment]
hi @coos60 ,
the artifact [Generic.Scanner.ThorZIP](https://github.com/NextronSystems/velociraptor-artifacts-thor/blob/master/artifacts/Generic.Scanner.ThorZIP.yaml) does not ask for api-keys/tokens. It just needs the THOR zip file (e.g. THOR lite which is free) and optionally additional cmdline args.

So for THOR lite you would [download](https://www.nextron-systems.com/thor-lite/) THOR lite, unpack it, add your THOR lite license, repack (everything) and upload it to the Generic.Scanner.ThorZIP artifact 'Tools -> ThorZIP'.

**Comment by pH-T** [comment]
hi @coos60 ,
you can also try [THOR cloud lite](https://thorcloud-lite.nextron-systems.com) with [Generic.Scanner.ThorCloud](https://github.com/NextronSystems/velociraptor-artifacts-thor/blob/master/artifacts/Generic.Scanner.ThorCloud.yaml) 
(you get the token param from the "Launcher" options http URL)

this might be easier/faster :)

**Comment by coos60** [comment]
thanks for the support. I solved it. The only problem with thor cloud lite running in velociraptor is the timeout. It fails to complete operations.

**Comment by pH-T** [comment]
hi @coos60 ,
nice to hear that!
true, the default timeout is not enough for running THOR. thats why we recommend a timeout of 30000 sec (~8.5h), e.g. [here](https://github.com/NextronSystems/velociraptor-artifacts-thor/blob/acecced22fb8cd228939945c5b0969fe3585eb12/artifacts/Generic.Scanner.ThorCloud.yaml#L8) .

**Comment by coos60** [comment]
Thanks @pH-T. I'm trying it now

**Comment by coos60** [comment]
it works!!!!

**Comment by coos60** [comment]
Thanks @pH-T. it works!!!!!!!!
