### ISSUE TITLE
False positive report

### ISSUE THREAD

**Issue by seeid10t** [NextronSystems/thor-lite#46]
Hello, first off, thank you very much, and I appreciate the Thor Lite product; however, I believe Thor Lite is giving a few false positives relating to ClamAV. I have duplicated the same response on two machines, and I believe that there is someone else who thinks his machine is infected by APT28 from the same false positives. I noticed he is running ClamAV as well. The steps to reproduce the false positives are simply to install ClamAV, and you will trigger the Yara rule. HKTL_Meterleter_inMemory. I added URLHaus and Securiteinfo signatures to ClamAV, and then you get even more false positives, including /usr/sbin/sshd, along with the initial /usr/sbin/clamd. SSHD binary and clamd binary check out as legit. At the very least, I figured I would post this for anyone else who might be experiencing the same thing and to allow anyone who might have a suggestion on this topic. Thank you. Have a good day.

**Comment by Neo23x0** [comment]
Thank you for your detailed report and for taking the time to share your observations.

The behavior you're describing is expected. ClamAV, being an antivirus engine, loads malware signatures into memory for detection purposes. These signatures can trigger YARA rules during a scan, leading to what appear as false positives.

Similarly, sshd might also show matches if it was used to transfer the THOR Lite scanner onto the target system. Certain patterns or clear-text rules can persist in the memory of the sshd daemon, causing detections.

While these detections are technically valid (as the signatures are indeed present in memory), they are not indicative of an active infection.

We appreciate you sharing this for others who might encounter the same scenario. If you have further questions or observations, feel free to let us know!
