### ISSUE TITLE
Cannot Update/Upgrade on Linux

### ISSUE THREAD

**Issue by prontosystems** [NextronSystems/thor-lite#6]
I am trying to update/upgrade signature/programm files on a Linux Debian 10 system but the command `thor-lite-util` fails:

`Apr 14 18:16:59 mail.domain.de THOR_LITE_UTIL: Info: Starting Upgrade Process
Apr 14 18:16:59 mail.domain.de THOR_LITE_UTIL: Info: License file found OWNER: Thomas Wildgruber (towi@domain.de) TYPE: THOR Lite STARTS: 2021/04/07 EXPIRES: 2022/04/15
Apr 14 18:16:59 mail.domain.de THOR_LITE_UTIL: Info: Downloading scanner 'signatures-lite'
Apr 14 18:16:59 mail.domain.de THOR_LITE_UTIL: Info: Downloading from: https://update1.nextron-systems.com/getliteupdate.php?full=1&lic=5b2e7fe8814922e8d11dfd2d898aadfe&product=signatures-lite&thorupgrader=1.10.5%2Bthor10.5.14&thorversion=21.4.8-171405&upgrade_only=1
Apr 14 18:17:00 mail.domain.de THOR_LITE_UTIL: Info: downloaded package as zip
Apr 14 18:17:00 mail.domain.de THOR_LITE_UTIL: Error: Received version 21.4.14-085924 is older than installed version 21.4.8-171405
Apr 14 18:17:00 mail.domain.de THOR_LITE_UTIL: Info: If you're using the TechPreview or SigDev, you may want to use the --techpreview / --sigdev flag to upgrade that version; otherwise use --force for a downgrade.`

None of the specified parameters to force the update works. Each of these parameters ends with an `Error: unknown flag` notification.

Thx in advance & Bye Tom

**Comment by Neo23x0** [comment]
Did you try `--force`? 
It's a known bug that'll be fixed soon. And no worries, the public `signature-base` repo hasn't got any important updates recently. You won't miss anything new.

**Comment by prontosystems** [comment]
Servus Neo,

Yes I used `--force` and there I get back the `THOR_LITE_UTIL: Error: unknown flag: --force`. Should I then download a newer version from your site when it is available or does the `thor-lite-util` do it on its own when the `upgrade` flag is in place? I ask this because there is currently a cronjob running daily and it would then fix this automatically as soon as it is available, otherwise I would have to keep an eye on your releases to replace it myself. 

Thx & Bye Tom

**Comment by Neo23x0** [comment]
We fixed it this afternoon. Could you check if it's fixed? 
It should heal itself with a `thor-lite-util upgrade`

**Comment by prontosystems** [comment]
Yes it works now. Thanks a lot, well done...

Bye Tom
