### ISSUE TITLE
FileScan and OneDrive Files on Demand

### ISSUE THREAD

**Issue by DirkRose** [NextronSystems/thor-lite#8]
Hi, first time user of thor-lite & I noticed that when the file scan hit a OneDrive directory with "online" files (files on-demand), it started downloading them all. This could be a major issue with local storage, is there a way to exclude OneDrive files on-demand?

**Comment by Neo23x0** [comment]
Could you check if you can simply add the folder in `./conf/directory-excludes.cfg`? 

e.g.
```
\\OneDrive\\
```

Quick check
```
thor64-lite.exe -a FileScan -p C:\Users\youruser\..
```

http://thor-manual.nextron-systems.com/en/latest/usage/configuration.html#files-and-directories

**Comment by DirkRose** [comment]
Thanks, I was looking for a way to exclude directories. This should do the trick.

**Comment by Neo23x0** [comment]
Did it work? 
There are some evaluations on folders even if they're defined in the `./conf/directory-excludes.cfg`. 
These evaluations could still trigger a download.

**Comment by DirkRose** [comment]
Yes, thankyou. Sorry for the time zone difference causing a delay.

**Comment by maxdd** [comment]
Is there a way to launch thor in "normal" mode with all the features but exclude a path?

`thor64-lite.exe -a FileScan -p C:\Users\youruser\..`

this command seems to "activate" only FileScan mode right?

**Comment by secDre4mer** [comment]
Yes, you can define file excludes as described here: https://thor-manual.nextron-systems.com/en/latest/usage/configuration.html#files-and-directories
